### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by lizellcode** [ymcmrs/ICAMS#4]
When I use your code to do atmosphere correction, an error occurred. 
----------- Step 2 --------------
Start to generate high-resolution tropospheric maps ...
Variogram model: Spherical
Number of bins: 50

Total number of data set: 21
Exsit number of data set: 0
Number of high-resolution maps need to be generated: 21
Date: 20141018 (1/21)
Average geoid height: -28.801188924026334
Kriging wet-delay levels: [##################################################] 100.0%    complete

Interpolating delay levels: [##################################################] 100.0%    complete

Traceback (most recent call last):
  File "/home/chenisce/tools/ICAMS/icams/tropo_icams_sar.py", line 509, in <module>
    main(sys.argv[:])
  File "/home/chenisce/tools/ICAMS/icams/tropo_icams_sar.py", line 480, in main
    sar_wet00  = linearint_wet(np.vstack((lala, lolo, hh)).T)
  File "/home/chenisce/miniconda3/envs/isce2/lib/python3.9/site-packages/scipy/interpolate/_rgi.py", line 331, in __call__
    indices, norm_distances = self._find_indices(xi.T)
  File "/home/chenisce/miniconda3/envs/isce2/lib/python3.9/site-packages/scipy/interpolate/_rgi.py", line 499, in _find_indices
    return find_indices(self.grid, xi)
  File "_rgi_cython.pyx", line 95, in scipy.interpolate._rgi_cython.find_indices
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: ndarray is not C-contiguous

Could you please help to figure out? thankss

**Comment by ymcmrs** [comment]
Can you please present the full command line here?

From: lizellcode ***@***.***>
Date: Tuesday, 13 June 2023 at 3:28 PM
To: ymcmrs/ICAMS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ymcmrs/ICAMS] ValueError: ndarray is not C-contiguous (Issue #4)

When I use your code to do atmosphere correction, an error occurred.
----------- Step 2 --------------
Start to generate high-resolution tropospheric maps ...
Variogram model: Spherical
Number of bins: 50

Total number of data set: 21
Exsit number of data set: 0
Number of high-resolution maps need to be generated: 21
Date: 20141018 (1/21)
Average geoid height: -28.801188924026334
Kriging wet-delay levels: [##################################################] 100.0% complete

Interpolating delay levels: [##################################################] 100.0% complete

Traceback (most recent call last):
File "/home/chenisce/tools/ICAMS/icams/tropo_icams_sar.py", line 509, in
main(sys.argv[:])
File "/home/chenisce/tools/ICAMS/icams/tropo_icams_sar.py", line 480, in main
sar_wet00 = linearint_wet(np.vstack((lala, lolo, hh)).T)
File "/home/chenisce/miniconda3/envs/isce2/lib/python3.9/site-packages/scipy/interpolate/_rgi.py", line 331, in call
indices, norm_distances = self._find_indices(xi.T)
File "/home/chenisce/miniconda3/envs/isce2/lib/python3.9/site-packages/scipy/interpolate/_rgi.py", line 499, in _find_indices
return find_indices(self.grid, xi)
File "_rgi_cython.pyx", line 95, in scipy.interpolate._rgi_cython.find_indices
File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
File "stringsource", line 350, in View.MemoryView.memoryview.cinit
ValueError: ndarray is not C-contiguous

Could you please help to figure out? thankss

**Comment by lizellcode** [comment]
I loaded interferograms into Mintpy, and inputted the command “tropo_icams.py timeseries.h5 inputs/geometryRadar.h5 --project zenith --method sklm”. The step 1 downloaded the ERA data successfully. But the step 2 popped out the error. I noticed that you suggested to install PyKrige from your url. My conda environment had PyKrige, so I did not reinstall it. I'm not sure whether the error was caused by the different version of PyKrige or not.

**Comment by ymcmrs** [comment]
Yes, please try to reinstall your PyKrige, and there are several changes from the original version.

From: lizellcode ***@***.***>
Date: Thursday, 15 June 2023 at 12:16 AM
To: ymcmrs/ICAMS ***@***.***>
Cc: Yunmeng Cao ***@***.***>, Comment ***@***.***>
Subject: Re: [ymcmrs/ICAMS] ValueError: ndarray is not C-contiguous (Issue #4)

I loaded interferograms into Mintpy, and inputted the command “tropo_icams.py timeseries.h5 inputs/geometryRadar.h5 --project zenith --method sklm”. The step 1 downloaded the ERA data successfully. But the step 2 popped out the error. I noticed that you suggested to install PyKrige from your url. My conda environment had PyKrige, so I did not reinstall it. I'm not sure whether the error was caused by the different version of PyKrige or not.

**Comment by lizellcode** [comment]
I reinstalled PyKrige and upgraded Scipy. The code works now. Thanks a lot!
